//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace FPZinfo.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService3")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/HelloWorld", ReplyAction="http://tempuri.org/IService1/HelloWorldResponse")]
        System.IAsyncResult BeginHelloWorld(string value, System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDatabaseString", ReplyAction="http://tempuri.org/IService1/GetDatabaseStringResponse")]
        System.IAsyncResult BeginGetDatabaseString(string pattern, string name, string lastname, System.AsyncCallback callback, object asyncState);
        
        string EndGetDatabaseString(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/ReadWrite_Image", ReplyAction="http://tempuri.org/IService1/ReadWrite_ImageResponse")]
        System.IAsyncResult BeginReadWrite_Image(string ime, string prezime, System.AsyncCallback callback, object asyncState);
        
        byte[] EndReadWrite_Image(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Nazocnost_profesora", ReplyAction="http://tempuri.org/IService1/Nazocnost_profesoraResponse")]
        System.IAsyncResult BeginNazocnost_profesora(string ime, string prezime, System.AsyncCallback callback, object asyncState);
        
        bool EndNazocnost_profesora(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Konzultacije", ReplyAction="http://tempuri.org/IService1/KonzultacijeResponse")]
        System.IAsyncResult BeginKonzultacije(string pattern, string ime, string prezime, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndKonzultacije(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAvailableRoom", ReplyAction="http://tempuri.org/IService1/GetAvailableRoomResponse")]
        System.IAsyncResult BeginGetAvailableRoom(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetAvailableRoom(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNastavnikFromDatabase", ReplyAction="http://tempuri.org/IService1/GetNastavnikFromDatabaseResponse")]
        System.IAsyncResult BeginGetNastavnikFromDatabase(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetNastavnikFromDatabase(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Populacijasrodnihprofesora", ReplyAction="http://tempuri.org/IService1/PopulacijasrodnihprofesoraResponse")]
        System.IAsyncResult BeginPopulacijasrodnihprofesora(string parameter_predmet, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndPopulacijasrodnihprofesora(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Spec_konzultacijeeeeee", ReplyAction="http://tempuri.org/IService1/Spec_konzultacijeeeeeeResponse")]
        System.IAsyncResult BeginSpec_konzultacijeeeeee(string pattern, string ime, string prezime, System.AsyncCallback callback, object asyncState);
        
        string EndSpec_konzultacijeeeeee(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetPredmetFromDatabase", ReplyAction="http://tempuri.org/IService1/GetPredmetFromDatabaseResponse")]
        System.IAsyncResult BeginGetPredmetFromDatabase(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetPredmetFromDatabase(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(FPZinfo.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        FPZinfo.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FPZinfo.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDatabaseStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDatabaseStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadWrite_ImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReadWrite_ImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Nazocnost_profesoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Nazocnost_profesoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KonzultacijeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public KonzultacijeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAvailableRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAvailableRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNastavnikFromDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNastavnikFromDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PopulacijasrodnihprofesoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PopulacijasrodnihprofesoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Spec_konzultacijeeeeeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Spec_konzultacijeeeeeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPredmetFromDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPredmetFromDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public FPZinfo.ServiceReference1.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((FPZinfo.ServiceReference1.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FPZinfo.ServiceReference1.IService1>, FPZinfo.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDatabaseStringDelegate;
        
        private EndOperationDelegate onEndGetDatabaseStringDelegate;
        
        private System.Threading.SendOrPostCallback onGetDatabaseStringCompletedDelegate;
        
        private BeginOperationDelegate onBeginReadWrite_ImageDelegate;
        
        private EndOperationDelegate onEndReadWrite_ImageDelegate;
        
        private System.Threading.SendOrPostCallback onReadWrite_ImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginNazocnost_profesoraDelegate;
        
        private EndOperationDelegate onEndNazocnost_profesoraDelegate;
        
        private System.Threading.SendOrPostCallback onNazocnost_profesoraCompletedDelegate;
        
        private BeginOperationDelegate onBeginKonzultacijeDelegate;
        
        private EndOperationDelegate onEndKonzultacijeDelegate;
        
        private System.Threading.SendOrPostCallback onKonzultacijeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAvailableRoomDelegate;
        
        private EndOperationDelegate onEndGetAvailableRoomDelegate;
        
        private System.Threading.SendOrPostCallback onGetAvailableRoomCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNastavnikFromDatabaseDelegate;
        
        private EndOperationDelegate onEndGetNastavnikFromDatabaseDelegate;
        
        private System.Threading.SendOrPostCallback onGetNastavnikFromDatabaseCompletedDelegate;
        
        private BeginOperationDelegate onBeginPopulacijasrodnihprofesoraDelegate;
        
        private EndOperationDelegate onEndPopulacijasrodnihprofesoraDelegate;
        
        private System.Threading.SendOrPostCallback onPopulacijasrodnihprofesoraCompletedDelegate;
        
        private BeginOperationDelegate onBeginSpec_konzultacijeeeeeeDelegate;
        
        private EndOperationDelegate onEndSpec_konzultacijeeeeeeDelegate;
        
        private System.Threading.SendOrPostCallback onSpec_konzultacijeeeeeeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPredmetFromDatabaseDelegate;
        
        private EndOperationDelegate onEndGetPredmetFromDatabaseDelegate;
        
        private System.Threading.SendOrPostCallback onGetPredmetFromDatabaseCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetDatabaseStringCompletedEventArgs> GetDatabaseStringCompleted;
        
        public event System.EventHandler<ReadWrite_ImageCompletedEventArgs> ReadWrite_ImageCompleted;
        
        public event System.EventHandler<Nazocnost_profesoraCompletedEventArgs> Nazocnost_profesoraCompleted;
        
        public event System.EventHandler<KonzultacijeCompletedEventArgs> KonzultacijeCompleted;
        
        public event System.EventHandler<GetAvailableRoomCompletedEventArgs> GetAvailableRoomCompleted;
        
        public event System.EventHandler<GetNastavnikFromDatabaseCompletedEventArgs> GetNastavnikFromDatabaseCompleted;
        
        public event System.EventHandler<PopulacijasrodnihprofesoraCompletedEventArgs> PopulacijasrodnihprofesoraCompleted;
        
        public event System.EventHandler<Spec_konzultacijeeeeeeCompletedEventArgs> Spec_konzultacijeeeeeeCompleted;
        
        public event System.EventHandler<GetPredmetFromDatabaseCompletedEventArgs> GetPredmetFromDatabaseCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginHelloWorld(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FPZinfo.ServiceReference1.IService1.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginHelloWorld(value, callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync(string value) {
            this.HelloWorldAsync(value, null);
        }
        
        public void HelloWorldAsync(string value, object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, new object[] {
                        value}, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginGetDatabaseString(string pattern, string name, string lastname, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDatabaseString(pattern, name, lastname, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FPZinfo.ServiceReference1.IService1.EndGetDatabaseString(System.IAsyncResult result) {
            return base.Channel.EndGetDatabaseString(result);
        }
        
        private System.IAsyncResult OnBeginGetDatabaseString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pattern = ((string)(inValues[0]));
            string name = ((string)(inValues[1]));
            string lastname = ((string)(inValues[2]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginGetDatabaseString(pattern, name, lastname, callback, asyncState);
        }
        
        private object[] OnEndGetDatabaseString(System.IAsyncResult result) {
            string retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndGetDatabaseString(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDatabaseStringCompleted(object state) {
            if ((this.GetDatabaseStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDatabaseStringCompleted(this, new GetDatabaseStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDatabaseStringAsync(string pattern, string name, string lastname) {
            this.GetDatabaseStringAsync(pattern, name, lastname, null);
        }
        
        public void GetDatabaseStringAsync(string pattern, string name, string lastname, object userState) {
            if ((this.onBeginGetDatabaseStringDelegate == null)) {
                this.onBeginGetDatabaseStringDelegate = new BeginOperationDelegate(this.OnBeginGetDatabaseString);
            }
            if ((this.onEndGetDatabaseStringDelegate == null)) {
                this.onEndGetDatabaseStringDelegate = new EndOperationDelegate(this.OnEndGetDatabaseString);
            }
            if ((this.onGetDatabaseStringCompletedDelegate == null)) {
                this.onGetDatabaseStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDatabaseStringCompleted);
            }
            base.InvokeAsync(this.onBeginGetDatabaseStringDelegate, new object[] {
                        pattern,
                        name,
                        lastname}, this.onEndGetDatabaseStringDelegate, this.onGetDatabaseStringCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginReadWrite_Image(string ime, string prezime, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReadWrite_Image(ime, prezime, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] FPZinfo.ServiceReference1.IService1.EndReadWrite_Image(System.IAsyncResult result) {
            return base.Channel.EndReadWrite_Image(result);
        }
        
        private System.IAsyncResult OnBeginReadWrite_Image(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ime = ((string)(inValues[0]));
            string prezime = ((string)(inValues[1]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginReadWrite_Image(ime, prezime, callback, asyncState);
        }
        
        private object[] OnEndReadWrite_Image(System.IAsyncResult result) {
            byte[] retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndReadWrite_Image(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReadWrite_ImageCompleted(object state) {
            if ((this.ReadWrite_ImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReadWrite_ImageCompleted(this, new ReadWrite_ImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReadWrite_ImageAsync(string ime, string prezime) {
            this.ReadWrite_ImageAsync(ime, prezime, null);
        }
        
        public void ReadWrite_ImageAsync(string ime, string prezime, object userState) {
            if ((this.onBeginReadWrite_ImageDelegate == null)) {
                this.onBeginReadWrite_ImageDelegate = new BeginOperationDelegate(this.OnBeginReadWrite_Image);
            }
            if ((this.onEndReadWrite_ImageDelegate == null)) {
                this.onEndReadWrite_ImageDelegate = new EndOperationDelegate(this.OnEndReadWrite_Image);
            }
            if ((this.onReadWrite_ImageCompletedDelegate == null)) {
                this.onReadWrite_ImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadWrite_ImageCompleted);
            }
            base.InvokeAsync(this.onBeginReadWrite_ImageDelegate, new object[] {
                        ime,
                        prezime}, this.onEndReadWrite_ImageDelegate, this.onReadWrite_ImageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginNazocnost_profesora(string ime, string prezime, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginNazocnost_profesora(ime, prezime, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool FPZinfo.ServiceReference1.IService1.EndNazocnost_profesora(System.IAsyncResult result) {
            return base.Channel.EndNazocnost_profesora(result);
        }
        
        private System.IAsyncResult OnBeginNazocnost_profesora(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ime = ((string)(inValues[0]));
            string prezime = ((string)(inValues[1]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginNazocnost_profesora(ime, prezime, callback, asyncState);
        }
        
        private object[] OnEndNazocnost_profesora(System.IAsyncResult result) {
            bool retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndNazocnost_profesora(result);
            return new object[] {
                    retVal};
        }
        
        private void OnNazocnost_profesoraCompleted(object state) {
            if ((this.Nazocnost_profesoraCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Nazocnost_profesoraCompleted(this, new Nazocnost_profesoraCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Nazocnost_profesoraAsync(string ime, string prezime) {
            this.Nazocnost_profesoraAsync(ime, prezime, null);
        }
        
        public void Nazocnost_profesoraAsync(string ime, string prezime, object userState) {
            if ((this.onBeginNazocnost_profesoraDelegate == null)) {
                this.onBeginNazocnost_profesoraDelegate = new BeginOperationDelegate(this.OnBeginNazocnost_profesora);
            }
            if ((this.onEndNazocnost_profesoraDelegate == null)) {
                this.onEndNazocnost_profesoraDelegate = new EndOperationDelegate(this.OnEndNazocnost_profesora);
            }
            if ((this.onNazocnost_profesoraCompletedDelegate == null)) {
                this.onNazocnost_profesoraCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnNazocnost_profesoraCompleted);
            }
            base.InvokeAsync(this.onBeginNazocnost_profesoraDelegate, new object[] {
                        ime,
                        prezime}, this.onEndNazocnost_profesoraDelegate, this.onNazocnost_profesoraCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginKonzultacije(string pattern, string ime, string prezime, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginKonzultacije(pattern, ime, prezime, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> FPZinfo.ServiceReference1.IService1.EndKonzultacije(System.IAsyncResult result) {
            return base.Channel.EndKonzultacije(result);
        }
        
        private System.IAsyncResult OnBeginKonzultacije(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pattern = ((string)(inValues[0]));
            string ime = ((string)(inValues[1]));
            string prezime = ((string)(inValues[2]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginKonzultacije(pattern, ime, prezime, callback, asyncState);
        }
        
        private object[] OnEndKonzultacije(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndKonzultacije(result);
            return new object[] {
                    retVal};
        }
        
        private void OnKonzultacijeCompleted(object state) {
            if ((this.KonzultacijeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.KonzultacijeCompleted(this, new KonzultacijeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void KonzultacijeAsync(string pattern, string ime, string prezime) {
            this.KonzultacijeAsync(pattern, ime, prezime, null);
        }
        
        public void KonzultacijeAsync(string pattern, string ime, string prezime, object userState) {
            if ((this.onBeginKonzultacijeDelegate == null)) {
                this.onBeginKonzultacijeDelegate = new BeginOperationDelegate(this.OnBeginKonzultacije);
            }
            if ((this.onEndKonzultacijeDelegate == null)) {
                this.onEndKonzultacijeDelegate = new EndOperationDelegate(this.OnEndKonzultacije);
            }
            if ((this.onKonzultacijeCompletedDelegate == null)) {
                this.onKonzultacijeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnKonzultacijeCompleted);
            }
            base.InvokeAsync(this.onBeginKonzultacijeDelegate, new object[] {
                        pattern,
                        ime,
                        prezime}, this.onEndKonzultacijeDelegate, this.onKonzultacijeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginGetAvailableRoom(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAvailableRoom(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> FPZinfo.ServiceReference1.IService1.EndGetAvailableRoom(System.IAsyncResult result) {
            return base.Channel.EndGetAvailableRoom(result);
        }
        
        private System.IAsyncResult OnBeginGetAvailableRoom(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginGetAvailableRoom(callback, asyncState);
        }
        
        private object[] OnEndGetAvailableRoom(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndGetAvailableRoom(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAvailableRoomCompleted(object state) {
            if ((this.GetAvailableRoomCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAvailableRoomCompleted(this, new GetAvailableRoomCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAvailableRoomAsync() {
            this.GetAvailableRoomAsync(null);
        }
        
        public void GetAvailableRoomAsync(object userState) {
            if ((this.onBeginGetAvailableRoomDelegate == null)) {
                this.onBeginGetAvailableRoomDelegate = new BeginOperationDelegate(this.OnBeginGetAvailableRoom);
            }
            if ((this.onEndGetAvailableRoomDelegate == null)) {
                this.onEndGetAvailableRoomDelegate = new EndOperationDelegate(this.OnEndGetAvailableRoom);
            }
            if ((this.onGetAvailableRoomCompletedDelegate == null)) {
                this.onGetAvailableRoomCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAvailableRoomCompleted);
            }
            base.InvokeAsync(this.onBeginGetAvailableRoomDelegate, null, this.onEndGetAvailableRoomDelegate, this.onGetAvailableRoomCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginGetNastavnikFromDatabase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNastavnikFromDatabase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> FPZinfo.ServiceReference1.IService1.EndGetNastavnikFromDatabase(System.IAsyncResult result) {
            return base.Channel.EndGetNastavnikFromDatabase(result);
        }
        
        private System.IAsyncResult OnBeginGetNastavnikFromDatabase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginGetNastavnikFromDatabase(callback, asyncState);
        }
        
        private object[] OnEndGetNastavnikFromDatabase(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndGetNastavnikFromDatabase(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNastavnikFromDatabaseCompleted(object state) {
            if ((this.GetNastavnikFromDatabaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNastavnikFromDatabaseCompleted(this, new GetNastavnikFromDatabaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNastavnikFromDatabaseAsync() {
            this.GetNastavnikFromDatabaseAsync(null);
        }
        
        public void GetNastavnikFromDatabaseAsync(object userState) {
            if ((this.onBeginGetNastavnikFromDatabaseDelegate == null)) {
                this.onBeginGetNastavnikFromDatabaseDelegate = new BeginOperationDelegate(this.OnBeginGetNastavnikFromDatabase);
            }
            if ((this.onEndGetNastavnikFromDatabaseDelegate == null)) {
                this.onEndGetNastavnikFromDatabaseDelegate = new EndOperationDelegate(this.OnEndGetNastavnikFromDatabase);
            }
            if ((this.onGetNastavnikFromDatabaseCompletedDelegate == null)) {
                this.onGetNastavnikFromDatabaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNastavnikFromDatabaseCompleted);
            }
            base.InvokeAsync(this.onBeginGetNastavnikFromDatabaseDelegate, null, this.onEndGetNastavnikFromDatabaseDelegate, this.onGetNastavnikFromDatabaseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginPopulacijasrodnihprofesora(string parameter_predmet, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPopulacijasrodnihprofesora(parameter_predmet, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> FPZinfo.ServiceReference1.IService1.EndPopulacijasrodnihprofesora(System.IAsyncResult result) {
            return base.Channel.EndPopulacijasrodnihprofesora(result);
        }
        
        private System.IAsyncResult OnBeginPopulacijasrodnihprofesora(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string parameter_predmet = ((string)(inValues[0]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginPopulacijasrodnihprofesora(parameter_predmet, callback, asyncState);
        }
        
        private object[] OnEndPopulacijasrodnihprofesora(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndPopulacijasrodnihprofesora(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPopulacijasrodnihprofesoraCompleted(object state) {
            if ((this.PopulacijasrodnihprofesoraCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PopulacijasrodnihprofesoraCompleted(this, new PopulacijasrodnihprofesoraCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PopulacijasrodnihprofesoraAsync(string parameter_predmet) {
            this.PopulacijasrodnihprofesoraAsync(parameter_predmet, null);
        }
        
        public void PopulacijasrodnihprofesoraAsync(string parameter_predmet, object userState) {
            if ((this.onBeginPopulacijasrodnihprofesoraDelegate == null)) {
                this.onBeginPopulacijasrodnihprofesoraDelegate = new BeginOperationDelegate(this.OnBeginPopulacijasrodnihprofesora);
            }
            if ((this.onEndPopulacijasrodnihprofesoraDelegate == null)) {
                this.onEndPopulacijasrodnihprofesoraDelegate = new EndOperationDelegate(this.OnEndPopulacijasrodnihprofesora);
            }
            if ((this.onPopulacijasrodnihprofesoraCompletedDelegate == null)) {
                this.onPopulacijasrodnihprofesoraCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPopulacijasrodnihprofesoraCompleted);
            }
            base.InvokeAsync(this.onBeginPopulacijasrodnihprofesoraDelegate, new object[] {
                        parameter_predmet}, this.onEndPopulacijasrodnihprofesoraDelegate, this.onPopulacijasrodnihprofesoraCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginSpec_konzultacijeeeeee(string pattern, string ime, string prezime, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSpec_konzultacijeeeeee(pattern, ime, prezime, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FPZinfo.ServiceReference1.IService1.EndSpec_konzultacijeeeeee(System.IAsyncResult result) {
            return base.Channel.EndSpec_konzultacijeeeeee(result);
        }
        
        private System.IAsyncResult OnBeginSpec_konzultacijeeeeee(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string pattern = ((string)(inValues[0]));
            string ime = ((string)(inValues[1]));
            string prezime = ((string)(inValues[2]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginSpec_konzultacijeeeeee(pattern, ime, prezime, callback, asyncState);
        }
        
        private object[] OnEndSpec_konzultacijeeeeee(System.IAsyncResult result) {
            string retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndSpec_konzultacijeeeeee(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSpec_konzultacijeeeeeeCompleted(object state) {
            if ((this.Spec_konzultacijeeeeeeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Spec_konzultacijeeeeeeCompleted(this, new Spec_konzultacijeeeeeeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Spec_konzultacijeeeeeeAsync(string pattern, string ime, string prezime) {
            this.Spec_konzultacijeeeeeeAsync(pattern, ime, prezime, null);
        }
        
        public void Spec_konzultacijeeeeeeAsync(string pattern, string ime, string prezime, object userState) {
            if ((this.onBeginSpec_konzultacijeeeeeeDelegate == null)) {
                this.onBeginSpec_konzultacijeeeeeeDelegate = new BeginOperationDelegate(this.OnBeginSpec_konzultacijeeeeee);
            }
            if ((this.onEndSpec_konzultacijeeeeeeDelegate == null)) {
                this.onEndSpec_konzultacijeeeeeeDelegate = new EndOperationDelegate(this.OnEndSpec_konzultacijeeeeee);
            }
            if ((this.onSpec_konzultacijeeeeeeCompletedDelegate == null)) {
                this.onSpec_konzultacijeeeeeeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSpec_konzultacijeeeeeeCompleted);
            }
            base.InvokeAsync(this.onBeginSpec_konzultacijeeeeeeDelegate, new object[] {
                        pattern,
                        ime,
                        prezime}, this.onEndSpec_konzultacijeeeeeeDelegate, this.onSpec_konzultacijeeeeeeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginGetPredmetFromDatabase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPredmetFromDatabase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> FPZinfo.ServiceReference1.IService1.EndGetPredmetFromDatabase(System.IAsyncResult result) {
            return base.Channel.EndGetPredmetFromDatabase(result);
        }
        
        private System.IAsyncResult OnBeginGetPredmetFromDatabase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginGetPredmetFromDatabase(callback, asyncState);
        }
        
        private object[] OnEndGetPredmetFromDatabase(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndGetPredmetFromDatabase(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPredmetFromDatabaseCompleted(object state) {
            if ((this.GetPredmetFromDatabaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPredmetFromDatabaseCompleted(this, new GetPredmetFromDatabaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPredmetFromDatabaseAsync() {
            this.GetPredmetFromDatabaseAsync(null);
        }
        
        public void GetPredmetFromDatabaseAsync(object userState) {
            if ((this.onBeginGetPredmetFromDatabaseDelegate == null)) {
                this.onBeginGetPredmetFromDatabaseDelegate = new BeginOperationDelegate(this.OnBeginGetPredmetFromDatabase);
            }
            if ((this.onEndGetPredmetFromDatabaseDelegate == null)) {
                this.onEndGetPredmetFromDatabaseDelegate = new EndOperationDelegate(this.OnEndGetPredmetFromDatabase);
            }
            if ((this.onGetPredmetFromDatabaseCompletedDelegate == null)) {
                this.onGetPredmetFromDatabaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPredmetFromDatabaseCompleted);
            }
            base.InvokeAsync(this.onBeginGetPredmetFromDatabaseDelegate, null, this.onEndGetPredmetFromDatabaseDelegate, this.onGetPredmetFromDatabaseCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FPZinfo.ServiceReference1.IService1.BeginGetDataUsingDataContract(FPZinfo.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FPZinfo.ServiceReference1.CompositeType FPZinfo.ServiceReference1.IService1.EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            FPZinfo.ServiceReference1.CompositeType composite = ((FPZinfo.ServiceReference1.CompositeType)(inValues[0]));
            return ((FPZinfo.ServiceReference1.IService1)(this)).BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            FPZinfo.ServiceReference1.CompositeType retVal = ((FPZinfo.ServiceReference1.IService1)(this)).EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(FPZinfo.ServiceReference1.CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(FPZinfo.ServiceReference1.CompositeType composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FPZinfo.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<FPZinfo.ServiceReference1.IService1>, FPZinfo.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<FPZinfo.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(string value, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = value;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDatabaseString(string pattern, string name, string lastname, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = pattern;
                _args[1] = name;
                _args[2] = lastname;
                System.IAsyncResult _result = base.BeginInvoke("GetDatabaseString", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetDatabaseString(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetDatabaseString", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReadWrite_Image(string ime, string prezime, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = ime;
                _args[1] = prezime;
                System.IAsyncResult _result = base.BeginInvoke("ReadWrite_Image", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndReadWrite_Image(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("ReadWrite_Image", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginNazocnost_profesora(string ime, string prezime, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = ime;
                _args[1] = prezime;
                System.IAsyncResult _result = base.BeginInvoke("Nazocnost_profesora", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndNazocnost_profesora(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("Nazocnost_profesora", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginKonzultacije(string pattern, string ime, string prezime, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = pattern;
                _args[1] = ime;
                _args[2] = prezime;
                System.IAsyncResult _result = base.BeginInvoke("Konzultacije", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndKonzultacije(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("Konzultacije", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAvailableRoom(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAvailableRoom", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetAvailableRoom(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetAvailableRoom", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNastavnikFromDatabase(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetNastavnikFromDatabase", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetNastavnikFromDatabase(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetNastavnikFromDatabase", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPopulacijasrodnihprofesora(string parameter_predmet, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = parameter_predmet;
                System.IAsyncResult _result = base.BeginInvoke("Populacijasrodnihprofesora", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndPopulacijasrodnihprofesora(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("Populacijasrodnihprofesora", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSpec_konzultacijeeeeee(string pattern, string ime, string prezime, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = pattern;
                _args[1] = ime;
                _args[2] = prezime;
                System.IAsyncResult _result = base.BeginInvoke("Spec_konzultacijeeeeee", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSpec_konzultacijeeeeee(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Spec_konzultacijeeeeee", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPredmetFromDatabase(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPredmetFromDatabase", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetPredmetFromDatabase(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetPredmetFromDatabase", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDataUsingDataContract(FPZinfo.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = composite;
                System.IAsyncResult _result = base.BeginInvoke("GetDataUsingDataContract", _args, callback, asyncState);
                return _result;
            }
            
            public FPZinfo.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result) {
                object[] _args = new object[0];
                FPZinfo.ServiceReference1.CompositeType _result = ((FPZinfo.ServiceReference1.CompositeType)(base.EndInvoke("GetDataUsingDataContract", _args, result)));
                return _result;
            }
        }
    }
}
